In [17]:
import zipfile

zip_file_path = r'C:\Users\Yalavarthi Saadhika\Downloads\data (2).zip'

with zipfile.ZipFile(zip_file_path, mode="r") as arch:
    file_list = arch.namelist()
    for file in file_list:
        print(file)

zipped/Breaking Bad/
zipped/Breaking Bad/Breaking.Bad.S01_sub_en.zip
zipped/Breaking Bad/Breaking.Bad.S02_sub_en.zip
zipped/Breaking Bad/Breaking.Bad.S03_sub_en.zip
zipped/Breaking Bad/Breaking.Bad.S04_sub_en.zip
zipped/Breaking Bad/Breaking.Bad.S05_sub_en.zip
zipped/F R I E N D S/
zipped/F R I E N D S/Friends.S01.sub.en.allepisodes.zip
zipped/F R I E N D S/Friends.S02.sub.en.allepisodes.zip
zipped/F R I E N D S/Friends.S03.sub.en.allepisodes.zip
zipped/F R I E N D S/Friends.S04.sub.en.allepisodes.zip
zipped/F R I E N D S/Friends.S05.sub.en.allepisodes.zip
zipped/F R I E N D S/Friends.S06.sub.en.allepisodes.zip
zipped/F R I E N D S/Friends.S07.sub.en.allepisodes.zip
zipped/F R I E N D S/Friends.S08.sub.en.allepisodes.zip
zipped/F R I E N D S/Friends.S09.sub.en.allepisodes.zip
zipped/F R I E N D S/Friends.S10.sub.en.allepisodes.zip
zipped/HIMYM/
zipped/HIMYM/HIMYM-Season-01_en.zip
zipped/HIMYM/HIMYM-Season-02_en.zip
zipped/HIMYM/HIMYM-Season-03_en.zip
zipped/HIMYM/HIMYM-Season-04_en.zip

In [21]:

import zipfile
with zipfile.ZipFile(r'C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\Breaking Bad\Breaking.Bad.S02_sub_en.zip', 'r') as zipf:
    zipf.extractall(path=r'C:\Users\Yalavarthi Saadhika\Desktop\project3\breaking_bad')


In [2]:
import os
import zipfile

def unzip_files(zip_folders, destination_folder):
    # Create the common destination folder if it doesn't exist
    os.makedirs(destination_folder, exist_ok=True)

    # Iterate over each zip folder
    for zip_folder in zip_folders:
        # Iterate over each zip file in the current zip folder
        for zip_file in os.listdir(zip_folder):
            if zip_file.endswith(".zip"):
                zip_file_path = os.path.join(zip_folder, zip_file)

                # Extract the contents of the zip file into the common destination folder
                with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
                    zip_ref.extractall(destination_folder)

                print(f"Extracted {zip_file} from {zip_folder} to {destination_folder}")
if __name__ == "__main__":
    # Replace these paths with your actual paths
    zip_folders_paths = [r'C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\Breaking Bad', r'C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\F R I E N D S']
    common_destination_folder = r'C:\Users\Yalavarthi Saadhika\Desktop\project3\title'
    unzip_files(zip_folders_paths, common_destination_folder)

Extracted Breaking.Bad.S01_sub_en.zip from C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\Breaking Bad to C:\Users\Yalavarthi Saadhika\Desktop\project3\title
Extracted Breaking.Bad.S02_sub_en.zip from C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\Breaking Bad to C:\Users\Yalavarthi Saadhika\Desktop\project3\title
Extracted Breaking.Bad.S03_sub_en.zip from C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\Breaking Bad to C:\Users\Yalavarthi Saadhika\Desktop\project3\title
Extracted Breaking.Bad.S04_sub_en.zip from C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\Breaking Bad to C:\Users\Yalavarthi Saadhika\Desktop\project3\title
Extracted Breaking.Bad.S05_sub_en.zip from C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\Breaking Bad to C:\Users\Yalavarthi Saadhika\Desktop\project3\title
Extracted Friends.S01.sub.en.allepisodes.zip from C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\F R I E N D S to C:\Users\Yalavarthi Saadhika\Desktop\project3\title
Extracte

In [3]:
import os
import zipfile

def unzip_files(zip_folders, destination_folder):
    # Create the common destination folder if it doesn't exist
    os.makedirs(destination_folder, exist_ok=True)

    # Iterate over each zip folder
    for zip_folder in zip_folders:
        # Iterate over each zip file in the current zip folder
        for zip_file in os.listdir(zip_folder):
            if zip_file.endswith(".zip"):
                zip_file_path = os.path.join(zip_folder, zip_file)

                # Extract the contents of the zip file into the common destination folder
                with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
                    zip_ref.extractall(destination_folder)

                print(f"Extracted {zip_file} from {zip_folder} to {destination_folder}")
if __name__ == "__main__":
    # Replace these paths with your actual paths
    zip_folders_paths = [r'C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\HIMYM', r'C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\MCU']
    common_destination_folder = r'C:\Users\Yalavarthi Saadhika\Desktop\project3\title'

    unzip_files(zip_folders_paths, common_destination_folder)

Extracted HIMYM-Season-01_en.zip from C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\HIMYM to C:\Users\Yalavarthi Saadhika\Desktop\project3\title
Extracted HIMYM-Season-02_en.zip from C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\HIMYM to C:\Users\Yalavarthi Saadhika\Desktop\project3\title
Extracted HIMYM-Season-03_en.zip from C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\HIMYM to C:\Users\Yalavarthi Saadhika\Desktop\project3\title
Extracted HIMYM-Season-04_en.zip from C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\HIMYM to C:\Users\Yalavarthi Saadhika\Desktop\project3\title
Extracted HIMYM-Season-05_en.zip from C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\HIMYM to C:\Users\Yalavarthi Saadhika\Desktop\project3\title
Extracted HIMYM-Season-06_en.zip from C:\Users\Yalavarthi Saadhika\Desktop\project3\zipped\HIMYM to C:\Users\Yalavarthi Saadhika\Desktop\project3\title
Extracted HIMYM-Season-07_en.zip from C:\Users\Yalavarthi Saadhika\Desktop\project3\zipp

# Reading Files

In [6]:
import os
import pandas as pd

def read_files_from_folders(folders):
    file_data = []  # List to store file paths, names, and contents

    for folder in folders:
        print(f"Reading files from folder: {folder}")

        # Iterate over all files in the current folder
        for root, _, files in os.walk(folder):
            for file in files:
                file_path = os.path.join(root, file)

                # Read the contents of the file
                with open(file_path, 'r', encoding='latin-1') as file_handle:
                    file_contents = file_handle.read()

                # Append file path, name, and content to the list
                file_data.append({'File_Path': file_path, 'File_Name': file, 'File_Content': file_contents})

    return file_data

folders_to_read = [r'C:\Users\Yalavarthi Saadhika\Desktop\project3\title\BREAKING BAD',r'C:\Users\Yalavarthi Saadhika\Desktop\project3\title\FRIENDS',r'C:\Users\Yalavarthi Saadhika\Desktop\project3\title\HIMYM',r'C:\Users\Yalavarthi Saadhika\Desktop\project3\title\MCU']


files_data = read_files_from_folders(folders_to_read)

    # Create a DataFrame from the list
df = pd.DataFrame(files_data)

    # Display the DataFrame
print(df)


Reading files from folder: C:\Users\Yalavarthi Saadhika\Desktop\project3\title\BREAKING BAD
Reading files from folder: C:\Users\Yalavarthi Saadhika\Desktop\project3\title\FRIENDS
Reading files from folder: C:\Users\Yalavarthi Saadhika\Desktop\project3\title\HIMYM
Reading files from folder: C:\Users\Yalavarthi Saadhika\Desktop\project3\title\MCU
                                             File_Path  \
0    C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
1    C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
2    C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
3    C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
4    C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
..                                                 ...   
938  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
939  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
940  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
941  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
942  C:\Users\Y

# Read data into a DataFrame

In [7]:
df.head()

File_Path  \
0  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
1  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
2  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
3  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
4  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   

                                           File_Name  \
0         Breaking Bad - 1x01 - Pilot.DSR.0TV.en.srt   
1  Breaking Bad - 1x01 - Pilot.DVDRip.ORPHEUS.en.srt   
2  Breaking Bad - 1x02 - Cat's in the Bag....DSR....   
3  Breaking Bad - 1x02 - Cat's in the Bag....DVDR...   
4  Breaking Bad - 1x03 - ...and the Bag's in the ...   

                                        File_Content  
0  1\n00:02:15,273 --> 00:02:17,187\nMy name is\n...  
1  1\n00:01:09,386 --> 00:01:11,221\nOh, my god.\...  
2  1\n00:00:05,695 --> 00:00:07,790\nPreviously o...  
3  1\n00:00:20,838 --> 00:00:23,257\nAre you okay...  
4  1\n00:00:43,059 --> 00:00:44,757\nLet's break ...

In [8]:
df.shape

(943, 3)

In [10]:
pd.read_csv(r'C:\Users\Yalavarthi Saadhika\Desktop\project3\title.csv')

Unnamed: 0                                          File_Path  \
0            0  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
1            1  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
2            2  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
3            3  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
4            4  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
..         ...                                                ...   
82          82  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
83          83  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
84          84  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
85          85  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
86          86  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   

                                            File_Name  \
0          Breaking Bad - 1x01 - Pilot.DSR.0TV.en.srt   
1   Breaking Bad - 1x01 - Pilot.DVDRip.ORPHEUS.en.srt   
2   Breaking Bad - 1x02 - Cat's in the Bag....DSR....   
3   Breaking Bad - 1x02 - Cat's in the Bag....DVDR...   
4   Breaking Bad - 1x03 - ...and the Bag's in the ...   
..                                                ...   
82  Breaking Bad - 3x13 - Full Measure.HDTV.FQM.en...   
83  Breaking Bad - 4x01 - Box Cutter.720p HDTV.ore...   
84  Breaking Bad - 4x01 - Box Cutter.720p.WEB-DL.e...   
85   Breaking Bad - 4x01 - Box Cutter.HDTV.FQM.en.srt   
86  Breaking Bad - 4x02 - Thirty-Eight Snub.720p H...   

                                         File_Content  
0   1\n00:02:15,273 --> 00:02:17,187\nMy name is\n...  
1   1\n00:01:09,386 --> 00:01:11,221\nOh, my god.\...  
2   1\n00:00:05,695 --> 00:00:07,790\nPreviously o...  
3   1\n00:00:20,838 --> 00:00:23,257\nAre you okay...  
4   1\n00:00:43,059 --> 00:00:44,757\nLet's break ...  
..                                                ...  
82  1\n00:01:07,237 --> 00:01:08,637\n[knock on do...  
83  1\n00:00:00,370 --> 00:00:02,661\n<i>Last seas...  
84  1\n00:00:44,500 --> 00:00:45,968\nHow's it com...  
85  1\n00:00:00,021 --> 00:00:02,324\n<i>Last s...  
86  1\n00:00:00,189 --> 00:00:02,973\n<i>Previo...  

[87 rows x 4 columns]

# Clean the "file_content" by removing HTML Tags

In [11]:
import pandas as pd
from bs4 import BeautifulSoup

def remove_html_tags(html_text):
    # Parse the HTML text
    soup = BeautifulSoup(html_text, 'html.parser')

    # Extract the text content without HTML tags
    text_content = soup.get_text(separator=' ', strip=True)
    
    return text_content
    
df['Text_Content'] = df['File_Content'].apply(remove_html_tags)

C:\Users\Yalavarthi Saadhika\anaconda3\lib\site-packages\bs4\__init__.py:435: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  warnings.warn(


In [12]:
df['Text_Content']

0      1\n00:02:15,273 --> 00:02:17,187\nMy name is\n...
1      1\n00:01:09,386 --> 00:01:11,221\nOh, my god.\...
2      1\n00:00:05,695 --> 00:00:07,790\nPreviously o...
3      1\n00:00:20,838 --> 00:00:23,257\nAre you okay...
4      1\n00:00:43,059 --> 00:00:44,757\nLet's break ...
                             ...                        
938    1\n00:00:26,361 --> 00:00:28,196 This is th...
939    1\n00:01:24,209 --> 00:01:25,543\nWait for ...
940    1\n00:00:41,834 --> 00:00:43,877\nOh, great...
941    1\n00:00:54,888 --> 00:00:56,598 Now, I kno...
942    1\n00:00:39,039 --> 00:00:43,636 ODIN: Long be...
Name: Text_Content, Length: 943, dtype: object

In [13]:
df.head()

File_Path  \
0  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
1  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
2  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
3  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
4  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   

                                           File_Name  \
0         Breaking Bad - 1x01 - Pilot.DSR.0TV.en.srt   
1  Breaking Bad - 1x01 - Pilot.DVDRip.ORPHEUS.en.srt   
2  Breaking Bad - 1x02 - Cat's in the Bag....DSR....   
3  Breaking Bad - 1x02 - Cat's in the Bag....DVDR...   
4  Breaking Bad - 1x03 - ...and the Bag's in the ...   

                                        File_Content  \
0  1\n00:02:15,273 --> 00:02:17,187\nMy name is\n...   
1  1\n00:01:09,386 --> 00:01:11,221\nOh, my god.\...   
2  1\n00:00:05,695 --> 00:00:07,790\nPreviously o...   
3  1\n00:00:20,838 --> 00:00:23,257\nAre you okay...   
4  1\n00:00:43,059 --> 00:00:44,757\nLet's break ...   

                                        Text_Content  
0  1\n00:02:15,273 --> 00:02:17,187\nMy name is\n...  
1  1\n00:01:09,386 --> 00:01:11,221\nOh, my god.\...  
2  1\n00:00:05,695 --> 00:00:07,790\nPreviously o...  
3  1\n00:00:20,838 --> 00:00:23,257\nAre you okay...  
4  1\n00:00:43,059 --> 00:00:44,757\nLet's break ...

# Special Characters, digits, and applying lemmmatization

In [14]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer


In [15]:
lemmatizer = WordNetLemmatizer()

In [16]:
def preprocess(text):
    # Removing special characters and digits
    sentence = re.sub("[^a-zA-Z]", " ", text)
    
    # change sentence to lower case
    sentence = sentence.lower()

    # tokenize into words
    tokens = sentence.split()
    
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    
    preprocessed_text = ' '.join(tokens)

    return preprocessed_text

In [17]:
df['clean_text_lemma'] = df['Text_Content'].apply(preprocess)

df.head()

File_Path  \
0  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
1  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
2  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
3  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
4  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   

                                           File_Name  \
0         Breaking Bad - 1x01 - Pilot.DSR.0TV.en.srt   
1  Breaking Bad - 1x01 - Pilot.DVDRip.ORPHEUS.en.srt   
2  Breaking Bad - 1x02 - Cat's in the Bag....DSR....   
3  Breaking Bad - 1x02 - Cat's in the Bag....DVDR...   
4  Breaking Bad - 1x03 - ...and the Bag's in the ...   

                                        File_Content  \
0  1\n00:02:15,273 --> 00:02:17,187\nMy name is\n...   
1  1\n00:01:09,386 --> 00:01:11,221\nOh, my god.\...   
2  1\n00:00:05,695 --> 00:00:07,790\nPreviously o...   
3  1\n00:00:20,838 --> 00:00:23,257\nAre you okay...   
4  1\n00:00:43,059 --> 00:00:44,757\nLet's break ...   

                                        Text_Content  \
0  1\n00:02:15,273 --> 00:02:17,187\nMy name is\n...   
1  1\n00:01:09,386 --> 00:01:11,221\nOh, my god.\...   
2  1\n00:00:05,695 --> 00:00:07,790\nPreviously o...   
3  1\n00:00:20,838 --> 00:00:23,257\nAre you okay...   
4  1\n00:00:43,059 --> 00:00:44,757\nLet's break ...   

                                    clean_text_lemma  
0  my name is walter hartwell white i live at neg...  
1  oh my god christ shit oh god oh my god oh my g...  
2  previously on breaking bad i don t know what s...  
3  are you okay you are a lifesaver yeah man we c...  
4  let s break it down hydrogen what doe that giv...

In [18]:
def preprocess(text):
    # Removing special characters and digits
    sentence = re.sub("[^a-zA-Z]", " ", text)
    
    # change sentence to lower case
    sentence = sentence.lower()

    # tokenize into words
    tokens = sentence.split()
    
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    
    preprocessed_text = len(tokens)

    return preprocessed_text

In [19]:
df.shape

(943, 5)

In [20]:
df['text_len_lemma'] = df['clean_text_lemma'].apply(preprocess)

df.head()

File_Path  \
0  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
1  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
2  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
3  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
4  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   

                                           File_Name  \
0         Breaking Bad - 1x01 - Pilot.DSR.0TV.en.srt   
1  Breaking Bad - 1x01 - Pilot.DVDRip.ORPHEUS.en.srt   
2  Breaking Bad - 1x02 - Cat's in the Bag....DSR....   
3  Breaking Bad - 1x02 - Cat's in the Bag....DVDR...   
4  Breaking Bad - 1x03 - ...and the Bag's in the ...   

                                        File_Content  \
0  1\n00:02:15,273 --> 00:02:17,187\nMy name is\n...   
1  1\n00:01:09,386 --> 00:01:11,221\nOh, my god.\...   
2  1\n00:00:05,695 --> 00:00:07,790\nPreviously o...   
3  1\n00:00:20,838 --> 00:00:23,257\nAre you okay...   
4  1\n00:00:43,059 --> 00:00:44,757\nLet's break ...   

                                        Text_Content  \
0  1\n00:02:15,273 --> 00:02:17,187\nMy name is\n...   
1  1\n00:01:09,386 --> 00:01:11,221\nOh, my god.\...   
2  1\n00:00:05,695 --> 00:00:07,790\nPreviously o...   
3  1\n00:00:20,838 --> 00:00:23,257\nAre you okay...   
4  1\n00:00:43,059 --> 00:00:44,757\nLet's break ...   

                                    clean_text_lemma  text_len_lemma  
0  my name is walter hartwell white i live at neg...            3830  
1  oh my god christ shit oh god oh my god oh my g...            3924  
2  previously on breaking bad i don t know what s...            3039  
3  are you okay you are a lifesaver yeah man we c...            3131  
4  let s break it down hydrogen what doe that giv...            3240

In [21]:
df.shape

(943, 6)

# Drop less than 500 words

In [22]:
len(df[df.text_len_lemma < 500])

256

In [23]:
df[df.text_len_lemma < 500].head()

File_Path  \
560  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
561  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
562  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
563  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   
564  C:\Users\Yalavarthi Saadhika\Desktop\project3\...   

                                             File_Name  \
560  How I Met Your Mother - 3x01 - Wait For It....srt   
561  How I Met Your Mother - 3x02 - We're Not From ...   
562     How I Met Your Mother - 3x03 - Third Wheel.srt   
563     How I Met Your Mother - 3x04 - Little Boys.srt   
564  How I Met Your Mother - 3x05 - How I Met Every...   

                                          File_Content  \
560  1\n00:00:00,461 --> 00:00:03,401\nȍå åÇ, ÈíÔÊ...   
561  1\n00:00:00,500 --> 00:00:03,960\nÎÈ ... ÇÒÏæÇ...   
562  1\n00:00:00,523 --> 00:00:02,873\nȍå åÇ¡ ãíÏæ...   
563  1\n00:00:00,960 --> 00:00:02,910\nÔäÈå ÔÈ äíæí...   
564  1\n00:00:00,700 --> 00:00:02,320\nȍå åÇ¡ ÏÑ ...   

                                          Text_Content  \
560  1\n00:00:00,461 --> 00:00:03,401\nȍå åÇ, ÈíÔÊ...   
561  1\n00:00:00,500 --> 00:00:03,960\nÎÈ ... ÇÒÏæÇ...   
562  1\n00:00:00,523 --> 00:00:02,873\nȍå åÇ¡ ãíÏæ...   
563  1\n00:00:00,960 --> 00:00:02,910\nÔäÈå ÔÈ äíæí...   
564  1\n00:00:00,700 --> 00:00:02,320\nȍå åÇ¡ ÏÑ ...   

                                      clean_text_lemma  text_len_lemma  
560  mehrdadsh m shahiri m gmail com www free offli...              11  
561  a am ami amin aminx aminx aminx www free offli...              12  
562  mehrdadsh m shahiri m gmail com www free offli...              10  
563               mehrdadsh aminx www free offline com               6  
564  mehrdadsh m shahiri m gmail com www free offli...              16

In [24]:
data_500 = df[df.text_len_lemma < 500].index

df.drop(data_500 , inplace  = True)

In [25]:
df.shape

(687, 6)

In [26]:
df[df.text_len_lemma < 500]

Empty DataFrame
Columns: [File_Path, File_Name, File_Content, Text_Content, clean_text_lemma, text_len_lemma]
Index: []

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [28]:
vectorizer = TfidfVectorizer()

In [29]:
tfidf_matrix = vectorizer.fit_transform(df.clean_text_lemma)

In [30]:
len(vectorizer.vocabulary_)

24042

In [31]:
print(tfidf_matrix.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [32]:
feature_names = vectorizer.get_feature_names_out()

In [33]:
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)

In [34]:
tfidf_df

aa  aaaaaaaaaaaaa  aaah  aaahhh  aaand  aaay  aah  aahh  aahing  \
0    0.0            0.0   0.0     0.0    0.0   0.0  0.0   0.0     0.0   
1    0.0            0.0   0.0     0.0    0.0   0.0  0.0   0.0     0.0   
2    0.0            0.0   0.0     0.0    0.0   0.0  0.0   0.0     0.0   
3    0.0            0.0   0.0     0.0    0.0   0.0  0.0   0.0     0.0   
4    0.0            0.0   0.0     0.0    0.0   0.0  0.0   0.0     0.0   
..   ...            ...   ...     ...    ...   ...  ...   ...     ...   
682  0.0            0.0   0.0     0.0    0.0   0.0  0.0   0.0     0.0   
683  0.0            0.0   0.0     0.0    0.0   0.0  0.0   0.0     0.0   
684  0.0            0.0   0.0     0.0    0.0   0.0  0.0   0.0     0.0   
685  0.0            0.0   0.0     0.0    0.0   0.0  0.0   0.0     0.0   
686  0.0            0.0   0.0     0.0    0.0   0.0  0.0   0.0     0.0   

     aakonian  ...  zuckerberg  zuckerberging  zumba  zundung  zurich  zverik  \
0         0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
1         0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
2         0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
3         0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
4         0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
..        ...  ...         ...            ...    ...      ...     ...     ...   
682       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
683       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
684       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
685       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
686       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   

     zxy  zygomatic   zz  zzzzt  
0    0.0        0.0  0.0    0.0  
1    0.0        0.0  0.0    0.0  
2    0.0        0.0  0.0    0.0  
3    0.0        0.0  0.0    0.0  
4    0.0        0.0  0.0    0.0  
..   ...        ...  ...    ...  
682  0.0        0.0  0.0    0.0  
683  0.0        0.0  0.0    0.0  
684  0.0        0.0  0.0    0.0  
685  0.0        0.0  0.0    0.0  
686  0.0        0.0  0.0    0.0  

[687 rows x 24042 columns]

# Query Pocessing

In [35]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import pairwise

In [46]:
def text_similarity_finder(search_query, k):
    #  vectorizer the search query using the fitted vectorizer
    search_query_vector =  vectorizer.transform([search_query])

    # Similarity Calculation
    similarity_scores = pairwise.cosine_similarity(search_query_vector, tfidf_df).flatten()

    # Indices of similar documents
    similar_doc_indices = similarity_scores.argsort()

    # Ranking and Retrieval
    return tfidf_df.loc[similar_doc_indices].head(k)
similar_texts = text_similarity_finder(input("enter your query"), 10)
print(similar_texts)

enter your querypeter parker
      aa  aaaaaaaaaaaaa  aaah  aaahhh  aaand  aaay       aah  aahh  aahing  \
0    0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
440  0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
441  0.0            0.0   0.0     0.0    0.0   0.0  0.010492   0.0     0.0   
442  0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
443  0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
444  0.0            0.0   0.0     0.0    0.0   0.0  0.009935   0.0     0.0   
445  0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
446  0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
439  0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
447  0.0            0.0   0.0     0.0    0.0   0.0  0.014547   0.0     0.0   

     aakonian  ...  zuckerberg  zuckerberging  zumba  zundung  zurich  zverik  \
0         0.0  ...         0.0 

In [38]:
pip install --upgrade scikit-learn


     ---------------------------------------- 9.3/9.3 MB 3.8 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.1
    Uninstalling scikit-learn-1.2.1:
      Successfully uninstalled scikit-learn-1.2.1


In [39]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [40]:
from sklearn.metrics import pairwise_distances

In [43]:
#Function to find similar texts
def text_similarity_finder(search_query, k):
    #  vectoize the search query using the fitted vectorizer
    search_query_vector =  vectorizer.transform([search_query])

    # Similarity Calculation
    similarity_scores = pairwise.cosine_similarity(search_query_vector, tfidf_df).flatten()

    # Indices of similar documents
    similar_doc_indices = similarity_scores.argsort()

    # Ranking and Retrieval
    similar_texts = tfidf_df.iloc[similar_doc_indices[:k]]
    df_3 = pd.DataFrame(similar_texts)
    return df_3

similar_texts = text_similarity_finder(input("enter your query: "), 10)
similar_texts

enter your query: peter parker


aa  aaaaaaaaaaaaa  aaah  aaahhh  aaand  aaay       aah  aahh  aahing  \
0    0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
440  0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
441  0.0            0.0   0.0     0.0    0.0   0.0  0.010492   0.0     0.0   
442  0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
443  0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
444  0.0            0.0   0.0     0.0    0.0   0.0  0.009935   0.0     0.0   
445  0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
446  0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
439  0.0            0.0   0.0     0.0    0.0   0.0  0.000000   0.0     0.0   
447  0.0            0.0   0.0     0.0    0.0   0.0  0.014547   0.0     0.0   

     aakonian  ...  zuckerberg  zuckerberging  zumba  zundung  zurich  zverik  \
0         0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
440       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
441       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
442       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
443       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
444       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
445       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
446       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
439       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   
447       0.0  ...         0.0            0.0    0.0      0.0     0.0     0.0   

     zxy  zygomatic   zz  zzzzt  
0    0.0        0.0  0.0    0.0  
440  0.0        0.0  0.0    0.0  
441  0.0        0.0  0.0    0.0  
442  0.0        0.0  0.0    0.0  
443  0.0        0.0  0.0    0.0  
444  0.0        0.0  0.0    0.0  
445  0.0        0.0  0.0    0.0  
446  0.0        0.0  0.0    0.0  
439  0.0        0.0  0.0    0.0  
447  0.0        0.0  0.0    0.0  

[10 rows x 24042 columns]